#!/bin/sh

# system startup.

# expand the ramdisk
/usr/bin/extract /ramfs.img /dev/ram0

# mount ramdisk, proc, sysfs, pts
/bin/mount -t proc proc /proc
/bin/mount -t sysfs sysfs /sys
/bin/mount -t devpts devpts /dev/pts

# load ext2
/sbin/insmod /lib/modules/mbcache.ko
/sbin/insmod /lib/modules/ext2.ko

# mount ramdisk
/bin/mount -t ext2 /dev/ram0 /var
/bin/mkdir /var/run

# config eth0/28j60 MAC
/sbin/ifconfig eth0 hw ether DE:AD:BE:EF:FE:ED

/sbin/ifup -a

/usr/sbin/inetd

# remove kernel message
dmesg -n 1

# disable virtual console blanking
# /bin/echo -e '\033[9;0]\033[14;0]' > /dev/console


# disabled because of leds class support for LD3/LD4
## enable the board leds
#echo 109 > /sys/class/gpio/export
#echo 110 > /sys/class/gpio/export
#
## set the board leds as output
#echo high > /sys/class/gpio/gpio109/direction
#echo high > /sys/class/gpio/gpio110/direction
#
## clear the board leds
#echo 0 > /sys/class/gpio/gpio109/value
#echo 0 > /sys/class/gpio/gpio110/value

exit 0
